##
## Compile frontend
##
FROM node:buster-slim as builder

WORKDIR /app
COPY . /app
RUN npm install
RUN npm run build

##
## Production image
##
FROM nginx:alpine

COPY --from=builder /app/dist/angular /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

COPY .devcontainer/entrypoint.sh /entrypoint.sh
RUN chmod 755 /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

# run nginx
CMD ["nginx", "-g", "daemon off;"]