##
## Compile frontend
##
FROM node:buster-slim as builder

WORKDIR /app
COPY . /app
RUN npm install
RUN npm run build

##
## Production image
##
FROM nginx:alpine

RUN mkdir /app
WORKDIR /app

COPY --from=builder /app/dist/angular /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

# run nginx
CMD ["nginx", "-g", "daemon off;"]